version: '3.8'

services:
  cyclonedx-sca-visualizer:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cyclonedx_sca_visualizer_prod
    restart: always
    ports:
      - "8081:80"
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80/"]
      interval: 30s
      timeout: 5s
      retries: 3
